### ISSUE TITLE
Error fetching data

### ISSUE THREAD

**Issue by WWY507** [StamusNetworks/KTS7#2]
Dashboard/SN-ALERTS with error

Error fetching data
Bad Request
Error: Bad Request
    at Fetch._callee3$ (http://10.10.84.201/32141/bundles/commons.bundle.js:3:1292397)
    at l (http://10.10.84.201/32141/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:288:969217)
    at Generator._invoke (http://10.10.84.201/32141/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:288:968970)
    at Generator.forEach.e.<computed> [as next] (http://10.10.84.201/32141/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:288:969574)
    at asyncGeneratorStep (http://10.10.84.201/32141/bundles/commons.bundle.js:3:1285920)
    at _next (http://10.10.84.201/32141/bundles/commons.bundle.js:3:1286231)

**Comment by pevma** [comment]
Which ELKS stack version are you on ?
Is that error during import ?

**Comment by WWY507** [comment]
> Which ELKS stack version are you on ?
> Is that error during import ?


suricata 5.0.3
ELK7.8.1 
ubuntu18.04.5

 import normal，when i access Dashboard of SN-ALERTS with error

**Comment by pevma** [comment]
You might want to double check this doc -  https://github.com/StamusNetworks/SELKS/wiki/Kibana-did-not-load-properly
